baseURL = " https://huypg2.github.io/FCAJ-Workshop/"
languageCode = "vi-vn"
title = "Báo cáo thực tập"
defaultContentLanguage = "vi"

[params]
  author = "First Cloud Journey"
  description = "Báo cáo thực tập AWS"
  lastUpdated = "08/07/2026"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
